config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :job_details


  root :to => 'static_pages#home'
  
  get '/doors', to: 'static_pages#doors'
  get '/drawer_fronts', to: 'static_pages#drawer_fronts'
  get '/dovetail_drawers', to: 'static_pages#dovetail_drawers'
  # match '/search', to: 'static_pages#search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def doors
    if request.method == "POST"
      create_job_info(params)
      respond_to do |format|
        if @new_job.save
          format.html {}
          format.js {}
          format.json { render :json => @new_job }
        end
      end
    end
    if !params[:open_job].nil?
      @job_header = JobHeader.find(params[:open_job])
      @job_details = JobDetail.find(:all, :conditions => { :job_id => @job_header.id })
    end
    return
  end

  def drawer_fronts
    if request.method == "POST"
      create_job_info(params)
      respond_to do |format|
        if @new_job.save
          format.html {}
          format.js {}
          format.json { render :json => @new_job }
        end
      end
    end
    if !params[:open_job].nil?
      @job_header = JobHeader.find(params[:open_job])
      @job_details = JobDetail.find(:all, :conditions => { :job_id => @job_header.id })
    end
    return
  end

  def dovetail_drawers
    if request.method == "POST"
      create_job_info(params)
      respond_to do |format|
        if @new_job.save
          format.html {}
          format.js {}
          format.json { render :json => @new_job }
        end
      end
    end
    if !params[:open_job].nil?
      @job_header = JobHeader.find(params[:open_job])
      @job_details = JobDetail.find(:all, :conditions => { :job_id => @job_header.id })
    end
    return
  end

  def search
    if request.method == "GET" && !params[:jobs].nil?
      date_from = params[:date_from]
      date_to = params[:date_to]
      job_name = params[:jobs]
      if date_from.empty? && date_to.empty?
        if job_name == "All"
          @jobs = JobHeader.find(:all, :order => "job ASC" )
        else
          @jobs = JobHeader.where( "job = ?", job_name )
        end
      elsif date_from.empty? && !date_to.empty?
        date_to = Date.strptime(date_to, "%m/%d/%Y")
        if job_name == "All"
          @jobs = JobHeader.where( "date_due <= ?", date_to )
        else
          @jobs = JobHeader.where( "job = ? AND date_due <= ?", params[:jobs], date_to )
        end
      elsif !date_from.empty? && date_to.empty?
        date_from = Date.strptime(date_from, "%m/%d/%Y")
        if job_name == "All"
          @jobs = JobHeader.where( "date_due >= ?", date_from )
        else
          @jobs = JobHeader.where( "job = ? AND date_due >= ?", params[:jobs], date_from )
        end
      else
        date_from = Date.strptime(date_from, "%m/%d/%Y")
        date_to = Date.strptime(date_to, "%m/%d/%Y")
        if job_name == "All"
          @jobs = JobHeader.where( "date_due >= ? AND date_due <= ?", date_from, date_to )
        else
          @jobs = JobHeader.where( "job = ? AND date_due >= ? AND date_due <= ?", params[:jobs], date_from, date_to )
        end
      end
      @jobs.each do |j|
        j[:project_type] = j[:project].titleize
        if j.bottom_notes == "1"
          j[:pretty_bottom_notes] = "Recess Bottom 1/2, Removeable"
        elsif j.bottom_notes == "2"
          j[:pretty_bottom_notes] = "Recess Bottom 1/2, Stationary"
        elsif j.bottom_notes == "3"
          j[:pretty_bottom_notes] = "Recess Bottom 1/4, Removeable"
        elsif j.bottom_notes == "4"
          j[:pretty_bottom_notes] = "Recess Bottom 1/4, Stationary"
        else
          j[:pretty_bottom_notes] = ""
        end
      end
      respond_to do |format|
        format.html {}
        format.js {}
        format.json { render :json => @jobs }
      end
    else
      @jobs_list = JobHeader.all(:select => :job, :order => 'job ASC').collect { |j| j.job }
      @jobs_list = @jobs_list.uniq
    end
    return
  end


  def create_job_info(params) 
    job_header = params
    job = job_header[:job]
    wood_type = job_header[:wood_type]
    inside_edge = job_header[:inside_edge]
    outside_edge = job_header[:outside_edge]
    panel_profile = job_header[:panel_profile]
    if job_header[:date_due].nil?
      date_due = ""
    else
      date_due = job_header[:date_due].empty? ? "" : Date.strptime(job_header[:date_due], "%m/%d/%Y")
    end
    drawer_type = job_header[:drawer_type]
    bottom_type = job_header[:bottom_type]
    bottom_notes = job_header[:bottom_selector]
    project = job_header[:project]
    totals = job_header[:txt_totals]
    #get total of rows then subtract 1 so that we can start from 0
    row_tally = job_header[:row_tally].to_i - 1

    if params[:created_job].to_i > 0
      @new_job = JobHeader.find(params[:created_job].to_i)
      @new_job.update_attributes(:project => project, :job => job, :wood_type => wood_type, :inside_edge => inside_edge, :outside_edge => outside_edge, :panel_profile => panel_profile, :date_due => date_due, :drawer_type => drawer_type, :bottom_type => bottom_type, :bottom_notes => bottom_notes, :totals => totals)
      JobDetail.destroy_all(:job_id => params[:created_job].to_i)
    else
      @new_job = JobHeader.create(:job => job) do |j|
        j.project = project
        j.wood_type = wood_type
        j.inside_edge = inside_edge
        j.outside_edge = outside_edge
        j.panel_profile = panel_profile
        j.date_due = date_due
        j.drawer_type = drawer_type
        j.bottom_type = bottom_type
        j.bottom_notes = bottom_notes
        j.totals = totals
      end
    end
    @new_job.save

    job_details = job_header.except(:project, :job, :wood_type, :inside_edge, :outside_edge, :panel_profile, :date_due, :drawer_type, :bottom_type, :bottom_selector, :row_tally, :txt_totals)
    
    (0..row_tally).each do |x|
      i = x.to_s
      nbr = ("nbr_name_" + i).to_sym
      qty = ("qty_name_" + i).to_sym
      size = ("size_name_" + i).to_sym
      style = ("style_select_name_" + i).to_sym
      border = ("border_info_name_" + i).to_sym
      center = ("center_info_name_" + i).to_sym
      note = ("notes_name_" + i).to_sym
      door_no = job_details[nbr]
      door_qty = job_details[qty]
      door_size = job_details[size]
      door_style = job_details[style]
      style_rail = job_details[border]
      panel_info = job_details[center]
      notes = job_details[note]
      #skip blank or invalid lines
      job_details = job_details.except(nbr, qty, size, style, border, center, note)
      if (door_qty.empty? || door_size.empty?)
        next
      end

      @new_detail = JobDetail.create(:job_id => @new_job.id) do |d|
        d.door_no = door_no
        d.door_qty = door_qty
        d.door_size = door_size
        d.door_style = door_style
        d.style_rail_info = style_rail
        d.panel_info = panel_info
        d.notes = notes
      end
    end  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_alt_body_header.html.erb
<div>
  <div style='display: inline; position: relative; left: -72px;'>#</div>
  <div style='display: inline; position: relative; left: -25px;'>Qty</div>
  <div style='display: inline; position: relative; left: 15px;'>Drawer Size (W x D X H)</div>
  <div style='display: inline; position: relative; left: 115px;'>Select Style</div>
  <div style='display: inline; position: relative; left: 245px;'>Parts</div>
  <div style='display: inline; position: relative; left: 400px;'>Bottoms (W x D)</div>
  <div style='display: inline; position: relative; left: 530px;'>Notes</div>
</div>

app/views/layouts/_alt_header.html.erb
<% if !@job_header %>
  <% @job_header = {:id => 0, :job => "", :wood_type => "", :drawer_type => "", :bottom_type => "", :bottom_notes => "1", :totals => "" } %>
<% end %>
<div style="background-color: #eaeaea; position: relative; left: -45px; width: 1025px; text-align:center">
  <br />
  <div style="position: relative; left: 10px;">
    JOB: <%= text_field_tag 'job', @job_header[:job] %>
    <div style="display: inline; position: relative; left: 49px;">
      TYPE OF WOOD: <%= text_field_tag 'wood_type', @job_header[:wood_type] %>
    </div>
  </div>
  <div style="position: relative; left: -15px;">
    DRAWER TYPE: <%= text_field_tag 'drawer_type', @job_header[:drawer_type] %>
    <div style="display: inline; position: relative; left: 25px;">
      TYPE OF BOTTOMS: <%= text_field_tag 'bottom_type', @job_header[:bottom_type] %>
    </div>
  </div>
  <br />
  <div>
    NOTES: 
    <%= select_tag "bottom_selector", options_for_select({
      "Recess Bottom 1/2, Removeable" => "1",
      "Recess Bottom 1/2, Stationary" => "2",
      "Recess Bottom 1/4, Removeable" => "3",
      "Recess Bottom 1/4, Stationary" => "4"
    }, @job_header[:bottom_notes]), :style => 'width: 250px' %>
  </div>
</div>

app/views/layouts/_body.html.erb
<div style="width: 1250px; position: relative; left: -150px; height: 50px;">
  <%= text_field_tag 'nbr', nil, :style => 'width: 30px; font-family: monospace; position: relative; left: 60px;', maxlength: 3 %>

  <%= text_field_tag 'qty', nil, :style => 'width: 30px; font-family: monospace; position: relative; left: 80px;', maxlength: 3 %>

  <%= text_field_tag 'size', nil, :style => 'width: 160px; font-family: monospace; position: relative; left: 95px;', maxlength: 20 %>

  <%= select_tag "style_select", nil, :style => "width: 200px; font-family: monospace; position: relative; left: 125px;", :onChange => "highlight_info(this.id);" %>

  <%= content_tag(:span, nil, :style => "display: inline-block; font-family: monospace; position: absolute; left: 610px; border-bottom: 2px solid black;", :id => "style_rail_info") %>
  <%= hidden_field_tag "border_info", nil %>

  <%= content_tag(:span, nil, :style => "display: inline-block; font-family: monospace; position: absolute; left: 836px;", :id => "panel_info") %>
  <%= hidden_field_tag "center_info", nil %>

  <%= text_field_tag 'notes', nil, :style => 'width: 160px; font-family: monospace; position: absolute; left: 1025px;', maxlength: 20 %>
</div>

app/views/layouts/_body_header.html.erb
<div>
  <div style='display: inline; position: relative; left: -72px;'>#</div>
  <div style='display: inline; position: relative; left: -25px;'>Qty</div>
  <div style='display: inline; position: relative; left: 35px;'>Door Size (W x H)</div>
  <div style='display: inline; position: relative; left: 155px;'>Select Style</div>
  <div style='display: inline; position: relative; left: 275px;'>Style & Rail</div>
  <div style='display: inline; position: relative; left: 400px;'>Panel (W x H)</div>
  <div style='display: inline; position: relative; left: 540px;'>Notes</div>
</div>

app/views/layouts/_button_footer.html.erb
<br />
Totals: <%= text_field_tag "txt_totals", @job_header[:totals],:style => "width: 875px", readonly: true %>
<br />
<div>
  <div style="align: left;">
    <button class="btn btn-large btn-primary" type="button" onclick="add_rows();">Add Rows</button>
    <button class="btn btn-large btn-primary" type="button" onclick="calculate();">Calculate</button>
  </div>
  <%= hidden_field_tag "row_tally", 0 %>
  <%= hidden_field_tag "created_job", 0 %>
</div>

app/views/layouts/_drawer_front_body_header.html.erb
<div>
  <div style='display: inline; position: relative; left: -72px;'>#</div>
  <div style='display: inline; position: relative; left: -25px;'>Qty</div>
  <div style='display: inline; position: relative; left: 35px;'>Door Size (W x H)</div>
  <div style='display: inline; position: relative; left: 155px;'>Select Style</div>
  <div style='display: inline; position: relative; left: 275px;'>Parts F & B</div>
  <div style='display: inline; position: relative; left: 400px;'>Panel (W x H)</div>
  <div style='display: inline; position: relative; left: 540px;'>Notes</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Braeger Woodworking", root_path %>
    by Andrew Ayers
  </small>
</footer>

app/views/layouts/_job_header.html.erb
<% if !@job_header %>
  <% @job_header = {:id => 0, :job => "", :wood_type => "", :inside_edge => "", :outside_edge => "", :panel_profile => "", :totals => "" } %>
  <% date_due = "" %>
<% else %>
  <% date_due = @job_header[:date_due].nil? ? "" : @job_header[:date_due].strftime('%m/%d/%Y') %>
<% end %>
<div style="background-color: #eaeaea; position: relative; left: -45px; width: 1025px;">
  <br />
  <div style="position: relative; left: 87px;">
    JOB: <%= text_field_tag 'job', @job_header[:job] %>
    TYPE OF WOOD: <%= text_field_tag 'wood_type', @job_header[:wood_type] %>
    INSIDE EDGE: <%= text_field_tag 'inside_edge', @job_header[:inside_edge] %>
  </div>
  <div style="position: relative; left: 10px;">
    OUTSIDE EDGE: <%= text_field_tag 'outside_edge', @job_header[:outside_edge] %>
    <div style="display: inline; position: relative; left: 3px;">
      PANEL PROFILE: <%= text_field_tag 'panel_profile', @job_header[:panel_profile] %>
    </div>
    <div style="display: inline; position: relative; left: 21px;">
      DATE DUE: <%= date_field 'date_due', date_due %>
    </div>
  </div>
  <br />
</div>

app/views/static_pages/doors.html.erb
<!DOCTYPE html>
<html>
<head>
  <% content_for :title, "Braeger Woodworking Inc. | Doors" %>
  <title><%= content_for :title %></title>
</head>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Braeger Woodworking", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>
<form action="/doors" id="doors_form" method="post">
  <%= hidden_field_tag "project", "doors" %>
  <%= render 'layouts/job_header' %>
  <br />
  <div id="main_body">
    <%= render 'layouts/body_header' %>
  </div>
  <%= render 'layouts/button_footer' %>
</form>
<script>
  
  function add_options(){
    $('#style_select_' + row_count).append('<option value="0">Arch</option>');
    $('#style_select_' + row_count).append('<option value="1">Cathedral</option>');
    $('#style_select_' + row_count).append('<option value="2">Custom</option>');
    $('#style_select_' + row_count).append('<option value="3">Glass Arch</option>');
    $('#style_select_' + row_count).append('<option value="4">Glass Cathedral</option>');
    $('#style_select_' + row_count).append('<option value="5">Glass Square</option>');
    $('#style_select_' + row_count).append('<option value="6">Square</option>');
  }

  function calculate(){
    arr_total = [];
    arr_denom = [];
    $('#txt_totals').val("");
    var qty = op = style = panel_msg = style_rail_msg = bottom = "";
    for(var i = 0; i < row_count; i++){
      qty = $('#qty_' + i).val();
      op = $('#size_' + i).val();
      if(qty == "" && op == "") {
        $('#style_rail_info_' + i).html("");
        $('#panel_info_' + i).html("");
        $('#border_info_' + i).val("");
        $('#center_info_' + i).val("");
        $('#notes_' + i).parent().height(50);
        $('#notes_' + i).val("");
        check_existing_id(i);
      }
      if (!(qty == 0 || op == "") && op.match(/x/g).length == 1){
        style = $('#style_select_' + i).val();
        //skip processing when custom 
        if (style == 2) {
          continue;
        }
        panel_msg = "&nbsp;&nbsp;&nbsp;&nbsp;Glass";
        style_rail_msg = get_style_and_rail(qty, op.toUpperCase(), style);
        if(style != 2 && style != 3 && style != 4 && style != 5){
          panel_msg = get_panel_cabinets(qty, op.toUpperCase());
        }
        $('#style_rail_info_' + i).html(style_rail_msg);
        $('#panel_info_' + i).html(panel_msg);
        $('#border_info_' + i).val(style_rail_msg);
        $('#center_info_' + i).val(panel_msg);
        $('#style_rail_info_' + i).css({"color": "black"});
        $('#panel_info_' + i).css({"color": "black"});
        if(extra_room){
          $('#notes_' + i).parent().height(70);
          extra_room = false;
        }
      }
    }

    add_custom_values_to_totals();
  }

  function open_job_check(){
    var job_id = <%= @job_header[:id] %>;
    var regex = new RegExp(/<br/g);
    var breaks = 0;
    $('#created_job').val(job_id);
    if(job_id > 0){
      var job_info = <%= @job_details.to_json.html_safe %>;
      for(var i = 0; i < job_info.length; i++){
        if((i % 10) == 0 && i != 0){
          add_rows();
        }

        $('#nbr_' + i).val(job_info[i].door_no);
        $('#qty_' + i).val(job_info[i].door_qty);
        $('#size_' + i).val(job_info[i].door_size);
        $('#style_select_' + i).val(job_info[i].door_style);
        $('#style_rail_info_' + i).html(job_info[i].style_rail_info);
        $('#border_info_' + i).val(job_info[i].style_rail_info);
        $('#panel_info_' + i).html(job_info[i].panel_info);
        $('#center_info_' + i).val(job_info[i].panel_info);
        $('#notes_' + i).val(job_info[i].notes);
        
        breaks = job_info[i].style_rail_info.match(regex).length;
        if(breaks > 1) {
          $('#notes_' + i).parent().height(50 + ((breaks - 1) * 20));
        }
        //Add custom values to array for totals
        if ("<%= @job_header[:project] %>" == "doors"){
          if (job_info[i].door_style == 2) {
            var custom_info = job_info[i].style_rail_info.split("<br />");
            var height = width = 0;
            //add stiles to custom totals
            height = parseFloat(custom_info[0].substring(custom_info[0].indexOf("-") + 1, custom_info[0].indexOf("X") - 1));
            width = parseFloat(custom_info[0].substring(custom_info[0].indexOf("X") + 1, custom_info[0].indexOf("S") - 1));
            add_custom_values(i.toString(), job_info[i].door_qty * 2, height, width);

            //add heights to custom totals
            height = parseFloat(custom_info[1].substring(custom_info[1].indexOf("-") + 1, custom_info[1].indexOf("X") - 1));
            width = parseFloat(custom_info[1].substring(custom_info[1].indexOf("X") + 1, custom_info[1].indexOf("T") - 1));
            add_custom_values(i.toString(), job_info[i].door_qty, height, width);

            //add widths to custom totals
            height = parseFloat(custom_info[2].substring(custom_info[2].indexOf("-") + 1, custom_info[2].indexOf("X") - 1));
            width = parseFloat(custom_info[2].substring(custom_info[2].indexOf("X") + 1, custom_info[2].indexOf("B") - 1));
            add_custom_values(i.toString(), job_info[i].door_qty, height, width);
          }
        }
      }
    }
  }
  
  //function add_custom_values(id, qty, height, width)
</script>

app/views/static_pages/dovetail_drawers.html.erb
<!DOCTYPE html>
<html>
<head>
  <% content_for :title, "Braeger Woodworking Inc. | Dovetail Drawers" %>
  <title><%= content_for :title %></title>
</head>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Braeger Woodworking", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>
<form action="/dovetail_drawers" id="dovetail_drawers_form" method="post">
  <%= hidden_field_tag "project", "dovetail_drawers" %>
  <%= render 'layouts/alt_header' %>
  <br />
  <div id="main_body">
    <%= render 'layouts/alt_body_header' %>
  </div>
  <%= render 'layouts/button_footer' %>
</form>

<script>
  
  function add_options(){
    $('#style_select_' + row_count).append('<option value="0">Dovetail Regular</option>');
    $('#style_select_' + row_count).append('<option value="1">Dovetail Pullout</option>');
  }
  
  function calculate(){
    var qty = op = style = parts_msg = bottom = "";
    arr_total = [];
    arr_denom = [];
    $('#txt_totals').val("");
    for(var i = 0; i < row_count; i++){
      qty = $('#qty_' + i).val();
      op = $('#size_' + i).val();
      if(qty == "" && op == "") {
        $('#style_rail_info_' + i).html("");
        $('#panel_info_' + i).html("");
        $('#border_info_' + i).val("");
        $('#center_info_' + i).val("");
        $('#notes_' + i).parent().height(50);
        $('#notes_' + i).val("");
      }
      style = $('#style_select_' + i).val();
      bottom = $('#bottom_selector').val();
      if (!(qty == 0 || op == "")  && op.match(/x/g).length == 2){
        parts_msg = get_parts(qty, op.toUpperCase(), style, bottom);
        //bottom info is after the pipe
        $('#style_rail_info_' + i).html(parts_msg.substring(0, parts_msg.indexOf("|")));
        $('#panel_info_' + i).html(parts_msg.substring(parts_msg.indexOf("|") + 1));
        $('#border_info_' + i).val(parts_msg.substring(0, parts_msg.indexOf("|")));
        $('#center_info_' + i).val(parts_msg.substring(parts_msg.indexOf("|") + 1));
        $('#style_rail_info_' + i).css({"color": "black"});
        $('#panel_info_' + i).css({"color": "black"});
        //add break for 3rd line for pullout drawers
        if(style == "1"){
          $('#notes_' + i).parent().height(70);
        }
      }
    }
  }
  
  function open_job_check(){
    var job_id = <%= @job_header[:id] %>;
    var regex = new RegExp(/<br/g);
    var breaks = 0;
    $('#created_job').val(job_id);
    if(job_id > 0){
      var job_info = <%= @job_details.to_json.html_safe %>;
      for(var i = 0; i < job_info.length; i++){
        if((i % 10) == 0 && i != 0){
          add_rows();
        }

        $('#nbr_' + i).val(job_info[i].door_no);
        $('#qty_' + i).val(job_info[i].door_qty);
        $('#size_' + i).val(job_info[i].door_size);
        $('#style_select_' + i).val(job_info[i].door_style);
        $('#style_rail_info_' + i).html(job_info[i].style_rail_info);
        $('#border_info_' + i).val(job_info[i].style_rail_info);
        $('#panel_info_' + i).html(job_info[i].panel_info);
        $('#center_info_' + i).val(job_info[i].panel_info);
        $('#notes_' + i).val(job_info[i].notes);
        
        breaks = job_info[i].style_rail_info.match(regex).length;
        if(breaks > 1) {
          $('#notes_' + i).parent().height(70);
        }
      }
    }
  }
  
</script>

app/views/static_pages/drawer_fronts.html.erb
<!DOCTYPE html>
<html>
<head>
  <% content_for :title, "Braeger Woodworking Inc. | Drawer Fronts" %>
  <title><%= content_for :title %></title>
</head>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Braeger Woodworking", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>
<form action="/drawer_fronts" id="drawer_fronts_form" method="post">
  <%= hidden_field_tag "project", "drawer_fronts" %>
  <%= render 'layouts/job_header' %>
  <br />
  <div id="main_body">
    <%= render 'layouts/drawer_front_body_header' %>
  </div>
  <%= render 'layouts/button_footer' %>
</form>

<script>

  function add_options(){
    $('#style_select_' + row_count).append('<option value="0">5-piece, 1.25</option>');
    $('#style_select_' + row_count).append('<option value="1">5-piece, 1.50</option>');
    $('#style_select_' + row_count).append('<option value="2">5-piece, 1.75</option>');
    $('#style_select_' + row_count).append('<option value="3">5-piece, 2.25</option>');
    $('#style_select_' + row_count).append('<option value="4">Panel Front</option>');
    $('#style_select_' + row_count).append('<option value="5">Slab</option>');
  }
  
  function calculate(){
    var qty = op = style = pnlmsg = pnlinfo = "";
    arr_total = [];
    arr_denom = [];
    $('#txt_totals').val("");
    for(var i = 0; i < row_count; i++){
      qty = $('#qty_' + i).val();
      op = $('#size_' + i).val();
      if(qty == "" && op == "") {
        $('#style_rail_info_' + i).html("");
        $('#panel_info_' + i).html("");
        $('#border_info_' + i).val("");
        $('#center_info_' + i).val("");
        $('#notes_' + i).parent().height(50);
        $('#notes_' + i).val("");
      }
      style = $('#style_select_' + i).val();
      if (!(style == "4" || style == "5" || qty == 0 || op == "")  && op.match(/x/g).length == 1){
        pnlmsg = get_panel_fronts(qty, op.toUpperCase(), style);
        //panel info is after the pipe
        $('#style_rail_info_' + i).html(pnlmsg.substring(0, pnlmsg.indexOf("|")));
        $('#panel_info_' + i).html(pnlmsg.substring(pnlmsg.indexOf("|") + 1));
        $('#border_info_' + i).val(pnlmsg.substring(0, pnlmsg.indexOf("|")));
        $('#center_info_' + i).val(pnlmsg.substring(pnlmsg.indexOf("|") + 1));
        $('#style_rail_info_' + i).css({"color": "black"});
        $('#panel_info_' + i).css({"color": "black"});
      } else if(style == "4" || style == "5") {
        $('#style_rail_info_' + i).html("");
        $('#panel_info_' + i).html("");
      }
    }
  }
  
  function open_job_check(){
    var job_id = <%= @job_header[:id] %>;
    var regex = new RegExp(/<br/g);
    var breaks = 0;
    $('#created_job').val(job_id);
    if(job_id > 0){
      var job_info = <%= @job_details.to_json.html_safe %>;
      for(var i = 0; i < job_info.length; i++){
        if((i % 10) == 0 && i != 0){
          add_rows();
        }

        $('#nbr_' + i).val(job_info[i].door_no);
        $('#qty_' + i).val(job_info[i].door_qty);
        $('#size_' + i).val(job_info[i].door_size);
        $('#style_select_' + i).val(job_info[i].door_style);
        $('#style_rail_info_' + i).html(job_info[i].style_rail_info);
        $('#border_info_' + i).val(job_info[i].style_rail_info);
        $('#panel_info_' + i).html(job_info[i].panel_info);
        $('#center_info_' + i).val(job_info[i].panel_info);
        $('#notes_' + i).val(job_info[i].notes);
        
        breaks = job_info[i].style_rail_info.match(regex).length;
        if(breaks > 1) {
          $('#notes_' + i).parent().height(70);
        }
      }
    }
  }
  
</script>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<head>
  <% content_for :title, "Braeger Woodworking Inc. | Home" %>
  <title><%= content_for :title %></title>
</head>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Braeger Woodworking", root_path, id: "logo" %>
    </div>
  </div>
</header>
<div class="center hero-unit">
  <h1 id="welcome">Good Morning!</h1>
  <h2>
    Please select an application below
  </h2>
  <div></div>
  <div style="font-size: 20px; font-weight: bold;">
    <%= link_to "Dovetail Drawers", dovetail_drawers_path %>
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <%= link_to "Doors", doors_path %>       
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <%= link_to "Drawer Fronts", drawer_fronts_path %> 
  </div>
</div>

<script>
  var d = new Date().getHours();
  if(d >= 17) {
    document.getElementById("welcome").innerHTML = "Good Evening!";
  } else if(d > 11) {
    document.getElementById("welcome").innerHTML = "Good Afternoon!";
  }
</script>